name = "ArgParse"
uuid = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
version = "1.0.0"
author = ["Carlo Baldassi <carlobaldassi@gmail.com>"]

[deps]
TextWrap = "b718987f-49a8-5099-9789-dcd902bef87d"

[compat]
TextWrap = "≥ 0.1.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
